name: Workflow name

on: push

permissions:
  contents: read

jobs:
  compile:
    name: Compile C++
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile C++
      run: g++ -O3 ./moead/main.cpp ./moead/problem.cpp ./moead/genetic_operator.cpp ./moead/genetic.cpp ./moead/local_search.cpp ./moead/moead.cpp ./moead/random.cpp -o ./moead/main.exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: ./moead/main.exe

  run:
    name: Run C++
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        a: [200.40.1,200.40.2,200.40.3,200.40.4]
        b: [5000000]
        c: [0] 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download executable
      uses: actions/download-artifact@v4
      with:
        name: executable
        path: ./moead

    - name: Run executable
      run: |
        chmod +x ./moead/main.exe
        ./moead/main.exe ${{ matrix.a }} ${{ matrix.b }} ${{ matrix.c }}
    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: result-${{ matrix.a }} ${{ matrix.b }} ${{ matrix.c }}
        path: ./result.txt
