name: Workflow name

on: push

permissions:
  contents: read

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Display system info
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Info:"
          df -h
          echo "Installed Tools:"
          docker --version
          node --version
          python3 --version
          gcc --version